---
title: "R Shiny"
output: html_document
date: "2022-11-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("shinydashboard")
#install.packages("plotly")
#install.packages("geodata")

source('read_data.R')

## ui.R ##
library(shiny)
library(shinydashboard)
library(plotly)
library(geojsonio)
library(broom)
library(viridis)

## app.R ##
ui <- dashboardPage(
  dashboardHeader(title = "TIPAC"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Funding", tabName = "funding", icon = icon("hands-holding-circle")),
      menuItem("Population", tabName = "population", icon = icon("people-group")),
      menuItem("Medicine", tabName = "medicine", icon = icon("prescription-bottle-medical")),
      menuItem("Costs", tabName = "costs", icon = icon("coins"))
    )
  ),
  dashboardBody(
    tabItems(
      # Funding tab content
      tabItem(tabName = "funding",
        fluidRow(
          box(plotlyOutput("subactivity_cost_pie", height = 400)),
  
          box(
            title = "Controls",
            sliderInput("slider", "Number of observations:", 1, 100, 50)
          )
        )
      ),
  
      # Population tab content
      tabItem(tabName = "population",
        h2("Widgets tab content")
      ),
      
      # Medicine tab content
      tabItem(tabName = "medicine",
        h2("Widgets tab content"),
        column(width=12,
          box(plotOutput("disease_burden_map", height = 700)),
          fluidRow(
            box(selectInput("condition", "Condition:", colnames(target_population_df))),
            box(textOutput("description"))
          )
        )
      ),
      
      # Costs tab content
      tabItem(tabName = "costs",
        h2("Costs")
      )
    )
  )
)

server <- function(input, output) {
  output$subactivity_cost_pie <- renderPlotly({
    subactivity_df %>% 
        group_by(`Name of Activity`) %>% 
        summarize(mean=mean(`Cost of Subactivity in GNF`)) %>%
        plot_ly(labels = ~`Name of Activity`, values = ~mean, type = 'pie') %>% 
        layout(title = 'Cumulative Cost by Activity',
             xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
             showlegend = FALSE)
  })
  output$description <- renderText({
    input$condition
  })
  output$target_population_map <- renderPlot({
    spdf <- geojson_read("data/gadm41_GIN_2.json",  what="sp")
    spdf_fortified <- tidy(spdf)
    spdf_fortified$id <- spdf_fortified$id %>% as.factor()
    
    mapping <- read_csv("data/guinea_region_mapping.csv", col_types="ccff")
    join_df <- target_population_df %>% left_join(. , mapping, by=(c("District"="subregion")))
    spdf_fortified <- spdf_fortified %>% left_join(. , join_df, by=c("id"="subregion_id"))

    # fill NA with 0
    #spdf_fortified[[input$condition]][ is.na(spdf_fortified[[input$condition]]) ] = 0.0001
    
    ggplot() + 
      geom_polygon(data = spdf_fortified, aes(fill = .data[[input$condition]], x = long, y = lat, group = group), size=0, alpha=0.9) + 
      theme_void() + 
      scale_fill_viridis(trans = "log", name=paste("Number of individuals with ", input$condition), guide = guide_legend( keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), label.position = "bottom", title.position = 'top', nrow=1) ) +
      labs(
        title = "Guinea Disease Burden",
        subtitle = paste("Number of ", input$condition," per district")
      ) +
      theme(
        text = element_text(color = "#22211d"),
        plot.background = element_rect(fill = "#f5f5f2", color = NA),
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA),
    
        plot.title = element_text(size= 22, hjust=0.01, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
        plot.subtitle = element_text(size= 17, hjust=0.01, color = "#4e4d47", margin = margin(b = -0.1, t = 0.43, l = 2, unit = "cm")),
        plot.caption = element_text( size=12, color = "#4e4d47", margin = margin(b = 0.3, r=-99, unit = "cm") ),
    
        legend.position = c(0.7, 0.09)
      ) +
      coord_map()
  })
}
  
shinyApp(ui, server)
```

